trip_on_life_info:
    resource: "@TripOnLifeInfoBundle/Resources/config/routing.yml"
    prefix:   /

trip_on_life_blog:
    resource: "@TripOnLifeBlogBundle/Resources/config/routing.yml"
    prefix:   /

trip_on_life_photo:
    resource: "@TripOnLifePhotoBundle/Resources/config/routing.yml"
    prefix:   /


#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
