<?php

namespace TripOnLife\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $name
     * @return array
     */
    public function getPostsByBlogSectionName($name)
    {
        $qb = $this->createQueryBuilder('b')
            ->select('b')
            ->leftJoin('b.blogSection', 'bs')
            ->where('bs.name = :name')
            ->setParameter('name', $name)
            ->addOrderBy('b.created', 'DESC');
        ;

        return $qb->getQuery()->getResult();
    }

}
