<?php

namespace TripOnLife\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
