<?php

namespace TripOnLife\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
